name: app
description: SwarnaGram.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  image_picker: ^1.0.4
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  ionicons: ^0.2.2
  google_fonts: ^6.1.0
  googleapis: ^11.4.0
  http: ^1.1.0
  photo_view: ^0.14.0
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

  assets:
    - assets/fonts/Billabong.ttf
    - assets/images/
